import { getRandomCompanies } from './mockCompanies';

// Search suggestions and related terms for intelligent search
export const searchSuggestions = {
  designer: [
    "UI Designer",
    "UX Designer",
    "Graphic Designer",
    "Web Designer",
    "Product Designer",
    "Visual Designer",
    "Brand Designer",
    "Logo Designer",
    "Figma",
    "Adobe Creative Suite",
    "Sketch",
    "InVision",
    "Prototyping",
    "Wireframing",
    "User Research",
    "Design Systems",
    "Responsive Design",
  ],
  developer: [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "React Developer",
    "Node.js Developer",
    "Python Developer",
    "Java Developer",
    "JavaScript",
    "TypeScript",
    "PHP",
    "Ruby",
    "Go",
    "C#",
    "Swift",
    "Database",
    "API Development",
    "DevOps",
    "Cloud Computing",
  ],
  mobile: [
    "iOS Developer",
    "Android Developer",
    "React Native",
    "Flutter Developer",
    "Mobile App Developer",
    "Cross-platform",
    "Swift",
    "Kotlin",
    "Java",
    "App Store",
    "Google Play",
    "Mobile UI/UX",
    "Push Notifications",
  ],
  marketing: [
    "Digital Marketing",
    "SEO Specialist",
    "Content Marketing",
    "Social Media",
    "Email Marketing",
    "PPC",
    "Google Ads",
    "Facebook Ads",
    "Analytics",
    "Conversion Optimization",
    "Brand Strategy",
    "Growth Hacking",
  ],
  writing: [
    "Content Writer",
    "Copywriter",
    "Technical Writer",
    "Blog Writer",
    "SEO Writer",
    "Ghostwriter",
    "Editor",
    "Proofreader",
    "Translation",
    "Creative Writing",
    "Business Writing",
    "Academic Writing",
  ],
  video: [
    "Video Editor",
    "Motion Graphics",
    "Animation",
    "After Effects",
    "Premiere Pro",
    "Final Cut Pro",
    "3D Animation",
    "Video Production",
    "YouTube",
    "TikTok",
    "Instagram Reels",
    "Commercial Video",
  ],
  data: [
    "Data Scientist",
    "Data Analyst",
    "Machine Learning",
    "AI Engineer",
    "Python",
    "R",
    "SQL",
    "Tableau",
    "Power BI",
    "Big Data",
    "Statistics",
    "Predictive Analytics",
    "Data Visualization",
  ],
  consulting: [
    "Business Consultant",
    "Strategy Consultant",
    "IT Consultant",
    "Management Consultant",
    "Financial Advisor",
    "Legal Consultant",
    "HR Consultant",
    "Operations Consultant",
  ],
};

// Popular categories for freelancers
export const popularCategories = [
  {
    id: "web-development",
    name: "Web Development",
    description: "Frontend, backend, and full-stack development",
    icon: "🌐",
    count: "2,500+",
  },
  {
    id: "mobile-development",
    name: "Mobile Development",
    description: "iOS, Android, and cross-platform apps",
    icon: "📱",
    count: "1,800+",
  },
  {
    id: "design",
    name: "Design & Creative",
    description: "UI/UX, graphic design, and branding",
    icon: "🎨",
    count: "3,200+",
  },
  {
    id: "marketing",
    name: "Digital Marketing",
    description: "SEO, social media, and content marketing",
    icon: "📈",
    count: "1,900+",
  },
  {
    id: "writing",
    name: "Writing & Translation",
    description: "Content writing, copywriting, and translation",
    icon: "✍️",
    count: "2,100+",
  },
  {
    id: "video",
    name: "Video & Animation",
    description: "Video editing, motion graphics, and animation",
    icon: "🎬",
    count: "1,400+",
  },
  {
    id: "data-science",
    name: "Data Science",
    description: "Data analysis, ML, and AI development",
    icon: "📊",
    count: "900+",
  },
  {
    id: "consulting",
    name: "Business Consulting",
    description: "Strategy, management, and IT consulting",
    icon: "💼",
    count: "1,200+",
  },
];

// Recommended freelancers - curated list of top performers
export const recommendedFreelancers = [
  {
    id: "rec-1",
    name: "Sarah Johnson",
    title: "Senior Frontend Developer",
    description:
      "Expert React developer with 8+ years of experience building scalable web applications. Specialized in modern frontend technologies and performance optimization.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    hourlyRate: 85,
    rating: 4.9,
    reviews: 247,
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    location: "San Francisco, CA",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/sarah-johnson",
    payRate: "$85/hr",
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: "rec-2",
    name: "Michael Chen",
    title: "Lead UI/UX Designer",
    description:
      "Award-winning designer with expertise in user-centered design and design systems. 6+ years creating exceptional digital experiences.",
    skills: [
      "Figma",
      "Adobe Creative Suite",
      "Design Systems",
      "Prototyping",
      "User Research",
    ],
    hourlyRate: 75,
    rating: 4.8,
    reviews: 189,
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    location: "New York, NY",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/michael-chen",
    payRate: "$75/hr",
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: "rec-3",
    name: "Emily Rodriguez",
    title: "Full Stack Engineer",
    description:
      "Versatile full-stack developer with strong backend and frontend skills. Expert in building robust, scalable applications from concept to deployment.",
    skills: ["Node.js", "React", "Python", "PostgreSQL", "AWS"],
    hourlyRate: 90,
    rating: 4.9,
    reviews: 312,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    location: "Austin, TX",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/emily-rodriguez",
    payRate: "$90/hr",
    professionalExperience: getRandomCompanies(5),
  },
  {
    id: "rec-4",
    name: "David Kim",
    title: "Mobile App Specialist",
    description:
      "Mobile development expert with 7+ years building high-performance iOS and Android applications. Specialized in React Native and native development.",
    skills: ["React Native", "iOS", "Android", "Firebase", "Swift"],
    hourlyRate: 80,
    rating: 4.9,
    reviews: 203,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    location: "Seattle, WA",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/david-kim",
    payRate: "$80/hr",
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: "rec-5",
    name: "James Wilson",
    title: "Senior Data Scientist",
    description:
      "Data science expert with PhD in Machine Learning. 5+ years transforming complex data into actionable business insights using cutting-edge AI techniques.",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "R"],
    hourlyRate: 95,
    rating: 4.9,
    reviews: 145,
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    location: "Boston, MA",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/james-wilson",
    payRate: "$95/hr",
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: "rec-6",
    name: "Alex Thompson",
    title: "DevOps Architect",
    description:
      "Cloud infrastructure specialist with expertise in AWS, Docker, and Kubernetes. 6+ years optimizing deployment pipelines and system reliability.",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    hourlyRate: 88,
    rating: 4.8,
    reviews: 178,
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    imageUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    location: "Denver, CO",
    availability: "Available now",
    verified: true,
    profileUrl: "https://example.com/profile/alex-thompson",
    payRate: "$88/hr",
    professionalExperience: getRandomCompanies(4),
  },
];

// Mock freelancer data
export const mockFreelancers = [
  {
    id: 1,
    name: "Sarah Johnson",
    title: "Senior Frontend Developer",
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviews: 127,
    hourlyRate: 65,
    experienceYears: 8,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    location: "San Francisco, CA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: 2,
    name: "Michael Chen",
    title: "UI/UX Designer",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviews: 89,
    hourlyRate: 55,
    experienceYears: 6,
    skills: ["Figma", "Adobe Creative Suite", "Prototyping", "User Research"],
    location: "New York, NY",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    title: "Full Stack Developer",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviews: 156,
    hourlyRate: 75,
    experienceYears: 10,
    skills: ["Node.js", "React", "Python", "PostgreSQL"],
    location: "Austin, TX",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(5),
  },
  {
    id: 4,
    name: "David Kim",
    title: "Mobile App Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviews: 203,
    hourlyRate: 70,
    experienceYears: 12,
    skills: ["React Native", "iOS", "Android", "Firebase"],
    location: "Seattle, WA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(6),
  },
  {
    id: 5,
    name: "Lisa Wang",
    title: "Digital Marketing Specialist",
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviews: 94,
    hourlyRate: 45,
    experienceYears: 5,
    skills: ["SEO", "Google Ads", "Social Media", "Analytics"],
    location: "Los Angeles, CA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: 6,
    name: "Alex Thompson",
    title: "Backend Developer",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviews: 178,
    hourlyRate: 80,
    experienceYears: 9,
    skills: ["Python", "Django", "AWS", "Docker"],
    location: "Denver, CO",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: 7,
    name: "Maria Garcia",
    title: "Content Writer",
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviews: 112,
    hourlyRate: 35,
    experienceYears: 4,
    skills: ["Content Writing", "SEO", "Copywriting", "Blogging"],
    location: "Miami, FL",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(2),
  },
  {
    id: 8,
    name: "James Wilson",
    title: "Data Scientist",
    avatar:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviews: 145,
    hourlyRate: 90,
    experienceYears: 11,
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    location: "Boston, MA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(5),
  },
  {
    id: 9,
    name: "Sophie Brown",
    title: "Graphic Designer",
    avatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviews: 87,
    hourlyRate: 40,
    experienceYears: 3,
    skills: ["Adobe Creative Suite", "Branding", "Logo Design", "Print Design"],
    location: "Portland, OR",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(2),
  },
  {
    id: 10,
    name: "Robert Lee",
    title: "DevOps Engineer",
    avatar:
      "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviews: 134,
    hourlyRate: 85,
    experienceYears: 7,
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    location: "Chicago, IL",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: 11,
    name: "Amanda Davis",
    title: "Video Editor",
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviews: 76,
    hourlyRate: 50,
    experienceYears: 6,
    skills: [
      "Premiere Pro",
      "After Effects",
      "Motion Graphics",
      "Color Grading",
    ],
    location: "Nashville, TN",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: 12,
    name: "Carlos Martinez",
    title: "WordPress Developer",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    rating: 4.5,
    reviews: 98,
    hourlyRate: 45,
    experienceYears: 5,
    skills: ["WordPress", "PHP", "CSS", "Plugin Development"],
    location: "Phoenix, AZ",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(3),
  },
  {
    id: 13,
    name: "Jennifer Taylor",
    title: "UX Researcher",
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviews: 67,
    hourlyRate: 60,
    experienceYears: 8,
    skills: ["User Research", "Usability Testing", "Analytics", "Personas"],
    location: "Atlanta, GA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: 14,
    name: "Kevin Anderson",
    title: "React Native Developer",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviews: 143,
    hourlyRate: 70,
    experienceYears: 9,
    skills: ["React Native", "JavaScript", "Redux", "Firebase"],
    location: "San Diego, CA",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(4),
  },
  {
    id: 15,
    name: "Rachel Green",
    title: "SEO Specialist",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviews: 89,
    hourlyRate: 40,
    experienceYears: 4,
    skills: ["SEO", "Google Analytics", "Keyword Research", "Technical SEO"],
    location: "Orlando, FL",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(2),
  },
  {
    id: 16,
    name: "Thomas White",
    title: "Python Developer",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviews: 167,
    hourlyRate: 75,
    experienceYears: 10,
    skills: ["Python", "Django", "Flask", "PostgreSQL"],
    location: "Austin, TX",
    availability: "Available now",
    verified: true,
    professionalExperience: getRandomCompanies(5),
  },
];
