services:
  sourcelander-front:
    build:
      context: .
    networks:
      sourcelander:
        ipv4_address: 192.168.10.74
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "3020:3000"

networks:
  sourcelander:
    external: 
      name: nginx_nginx
