import {
  Code,
  Palette,
  Megaphone,
  PenTool,
  Camera,
  BarChart3,
} from "lucide-react";

export const projectTypes = {
  development: {
    name: "Development",
    icon: Code,
    features: [
      "User Authentication",
      "Payment Integration",
      "Admin Dashboard",
      "Mobile Responsive",
      "API Development",
      "Database Design",
      "Real-time Chat",
      "File Upload",
      "Search Functionality",
      "Analytics Dashboard",
      "Email Notifications",
      "Multi-language Support",
    ],
    technologies: [
      "React",
      "Node.js",
      "Python",
      "PHP",
      "Java",
      "C#",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "AWS",
      "Docker",
      "Kubernetes",
    ],
    deliverables: [
      "Source Code",
      "Documentation",
      "Deployment Guide",
      "User Manual",
      "API Documentation",
      "Testing Reports",
    ],
  },
  design: {
    name: "Design",
    icon: Palette,
    features: [
      "UI/UX Design",
      "Brand Identity",
      "Logo Design",
      "Website Design",
      "Mobile App Design",
      "Print Design",
      "Social Media Graphics",
      "Illustrations",
      "Icons",
      "Prototyping",
      "User Research",
      "Design Systems",
    ],
    technologies: [
      "Figma",
      "Adobe Creative Suite",
      "Sketch",
      "InVision",
      "Photoshop",
      "Illustrator",
      "XD",
      "Principle",
    ],
    deliverables: [
      "Design Files",
      "Style Guide",
      "Prototypes",
      "Brand Guidelines",
      "Mockups",
      "Design Documentation",
    ],
  },
  marketing: {
    name: "Marketing",
    icon: Megaphone,
    features: [
      "SEO Optimization",
      "Social Media Management",
      "Content Marketing",
      "Email Campaigns",
      "PPC Advertising",
      "Analytics Setup",
      "Lead Generation",
      "Brand Strategy",
      "Influencer Marketing",
      "Video Marketing",
      "Conversion Optimization",
      "Market Research",
    ],
    technologies: [
      "Google Analytics",
      "Facebook Ads",
      "Google Ads",
      "Mailchimp",
      "HubSpot",
      "Hootsuite",
      "Canva",
      "SEMrush",
    ],
    deliverables: [
      "Marketing Strategy",
      "Content Calendar",
      "Analytics Reports",
      "Campaign Assets",
      "Performance Reports",
      "ROI Analysis",
    ],
  },
  content: {
    name: "Content Creation",
    icon: PenTool,
    features: [
      "Blog Writing",
      "Copywriting",
      "Technical Writing",
      "Video Scripts",
      "Social Media Content",
      "Email Newsletters",
      "Case Studies",
      "White Papers",
      "Product Descriptions",
      "Press Releases",
      "Translation",
      "Editing",
    ],
    technologies: [
      "WordPress",
      "Medium",
      "Grammarly",
      "Hemingway",
      "Canva",
      "Adobe Premiere",
      "Final Cut Pro",
      "DaVinci Resolve",
    ],
    deliverables: [
      "Content Calendar",
      "SEO-Optimized Content",
      "Brand Voice Guide",
      "Content Templates",
      "Editorial Guidelines",
      "Performance Reports",
    ],
  },
  video: {
    name: "Video & Animation",
    icon: Camera,
    features: [
      "Video Editing",
      "Motion Graphics",
      "2D Animation",
      "3D Animation",
      "Video Production",
      "Color Grading",
      "Sound Design",
      "Video Effects",
      "Titles & Graphics",
      "Video Marketing",
      "YouTube Optimization",
      "Live Streaming",
    ],
    technologies: [
      "Adobe Premiere",
      "After Effects",
      "Final Cut Pro",
      "DaVinci Resolve",
      "Cinema 4D",
      "Blender",
      "Audacity",
      "OBS Studio",
    ],
    deliverables: [
      "Final Video Files",
      "Project Files",
      "Color Grading Presets",
      "Motion Graphics Templates",
      "Video Guidelines",
      "Performance Analytics",
    ],
  },
  data: {
    name: "Data & Analytics",
    icon: BarChart3,
    features: [
      "Data Analysis",
      "Machine Learning",
      "Statistical Modeling",
      "Data Visualization",
      "Predictive Analytics",
      "Business Intelligence",
      "A/B Testing",
      "Data Mining",
      "Report Generation",
      "Dashboard Creation",
      "Data Cleaning",
      "Performance Tracking",
    ],
    technologies: [
      "Python",
      "R",
      "SQL",
      "Tableau",
      "Power BI",
      "Excel",
      "TensorFlow",
      "Scikit-learn",
      "Pandas",
      "NumPy",
    ],
    deliverables: [
      "Data Reports",
      "Interactive Dashboards",
      "Analytics Models",
      "Data Documentation",
      "Insights Summary",
      "Recommendation Reports",
    ],
  },
};
